"""empty message

Revision ID: 9e6a9703d8f0
Revises: 6e99026d8ba5
Create Date: 2017-04-11 23:10:54.886029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6a9703d8f0'
down_revision = '6e99026d8ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_profile', ['userid'])
    op.drop_column('user_profile', 'confirm')
    op.create_unique_constraint(None, 'wishlist', ['userid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist', type_='unique')
    op.add_column('user_profile', sa.Column('confirm', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='unique')
    # ### end Alembic commands ###
